name: vib-ribbon (Europe)
options:
  # paths
  basename:    vib-ribbon
  base_path:   ..
  target_path: iso/MAIN_T.EXE
  asm_path:    asm/game/
  asset_path:  assets/
  src_path:    src/game/

  # compiler
  platform:    psx
  compiler:    GCC

  # disasm
  symbol_addrs_path:           config/symbols.sces028.txt
  undefined_funcs_auto_path:   config/undefined_funcs_auto.sces028.vib-ribbon.txt
  undefined_syms_auto_path:    config/undefined_syms_auto.sces028.vib-ribbon.txt
  find_file_boundaries:        yes
  use_legacy_include_asm:      no
  migrate_rodata_to_functions: yes
  disasm_unknown:              yes

  include_macro_inc:           no # don't write macro.inc to rodata files

  rodata_string_guesser_level: 2 # improve string detection

  gp_value: 0x80047EB8

  section_order:
    - .rodata
    - .text
    - .data
    - .bss

segments:
  - [0, header]
  - name:  vib-ribbon
    type:  code
    start: 0x00000800
    vram:  0x80019000
    subalign: 4
    subsegments:
       # rodata
      - [0x800, .rodata, VideoSys]
      - [0x87C, .rodata, 5FE8]
      - [0x914, .rodata, AudioSys]
      - [0x9E8, .rodata, InputSys]
      - [0xA44, rodata] # MemorySys
      - [0xC00, rodata] # FileSys
      - [0xEA4, rodata] # InputControl
      - [0xF74, rodata] # Movie.h
      - [0x1070, rodata] # E9A0
      - [0x1810, rodata]
      - [0x3F5C, rodata]
      - [0x4264, rodata]
      - [0x42A4, rodata]
      - [0x42E4, rodata]
      - [0x4304, rodata]
      - [0x432C, rodata]
      - [0x43E4, rodata]
      - [0x4604, rodata]
      - [0x4634, rodata]
      - [0x4664, rodata]
      - [0x46F4, rodata]
      - [0x4948, rodata]
      - [0x49B0, rodata]
      - [0x4C44, rodata]
      - [0x4C60, rodata]
      # .text
      - [0x4D58, c, VideoSys]
      - [0x5E58, c, FontHack] # FontHack
      - [0x5FE8, c] # CdSys
      - [0x68D4, c, AudioSys]
      - [0x7BB8, c, InputSys]
      - [0x8EFC, c, MemorySys]
      - [0xE9A0, c]
      - [0xF2DC, c]
      - [0x12250, c]
      - [0x13778, asm, entrypoint]
      - [0x13868, asm, psyq]
      - [0x13F18, asm]
      - [0x14348, asm]
      - [0x14428, asm]
      - [0x144A8, asm]
      - [0x19648, asm]
      - [0x19958, asm]
      - [0x19CD8, asm]
      - [0x1A144, asm]
      - [0x1A1A4, asm]
      - [0x1A204, asm]
      - [0x1A2E4, asm]
      - [0x1A4A4, asm]
      - [0x1A774, asm]
      - [0x1A834, asm]
      - [0x1A8B4, asm]
      - [0x1A984, asm]
      - [0x1AA04, asm]
      - [0x1AB30, asm]
      - [0x1B130, asm]
      - [0x1B790, asm]
      - [0x1B9FC, asm]
      - [0x1BA4C, asm]
      - [0x1BA8C, asm]
      - [0x1BCEC, asm]
      - [0x1CB0C, asm]
      - [0x1D4AC, asm]
      - [0x1D5FC, asm]
      - [0x1D8AC, asm]
      - [0x1D90C, asm]
      - [0x1D97C, asm]
      - [0x1D998, asm]
      - [0x1D9C8, asm]
      - [0x1E854, asm]
      - [0x1EBBC, asm]
      - [0x1EBDC, asm]
      - [0x1EBEC, asm]
      - [0x1EBFC, asm]
      - [0x1EC1C, asm]
      - [0x1ECDC, asm]
      - [0x1ED8C, asm]
      - [0x1EDFC, asm]
      - [0x1EE9C, asm]
      - [0x1EFAC, asm]
      - [0x1EFBC, asm]
      - [0x1F02C, asm]
      - [0x1F11C, asm]
      - [0x1F1BC, asm]
      - [0x1F1DC, asm]
      - [0x1F20C, asm]
      - [0x1F22C, asm]
      - [0x1F24C, asm]
      - [0x1F28C, asm]
      - [0x1F2DC, asm]
      - [0x1F35C, asm]
      - [0x1F42C, asm]
      - [0x1FAF0, asm]
      - [0x1FBB0, asm]
      - [0x1FC10, asm]
      - [0x20D9C, asm]
      - [0x21794, asm]
      - [0x22CC8, asm]
      - [0x22E28, asm]
      - [0x23138, asm]
      - [0x23168, asm]
      - [0x23178, asm]
      - [0x23188, asm]
      - [0x23EFC, asm]
      - [0x243BC, asm]
      - [0x24FD0, asm]
      - [0x2617C, asm] # handwritten
      - [0x2620C, asm]
      - [0x264CC, asm]
      - [0x2651C, asm]
      - [0x2653C, asm]
      - [0x2655C, asm]
      - [0x2659C, asm]
      - [0x2662C, asm]
      - [0x2665C, asm]
      - [0x2666C, asm]
      - [0x26ED4, asm]
      - [0x26FA4, asm]
      - [0x27084, asm]
      # data
      - [0x27118, data]
      # sdata
      - [0x2F6C0, data]
      # sbss
      - [0x2F964, data]
      # bss
      - [0x2F970, data]
      #- [0x2F92C, data] # bss
  - [0x30000]
